name: Bug report
description: File a bug report to help us improve
labels: ["\U0001F48A bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
        - For questions, ask in [Discussions](https://github.com/flamego/flamego/discussions).
        - Before you file an issue read the [Contributing guide](https://github.com/flamego/flamego/blob/main/.github/contributing.md).
        - Check to make sure someone hasn't already opened a similar [issue](https://github.com/flamego/flamego/issues).
  - type: dropdown
    attributes:
      label: Component
      description: Please specify which component you're reporting for.
      options:
        - Core framework
        - Middleware
    validations:
      required: true
  - type: input
    attributes:
      label: Middleware
      description: If this is for middleware, please specify the repository URL, e.g. "https://github.com/flamego/template". Otherwise, put "n/a".
      value: "https://github.com/flamego/"
    validations:
      required: false
  - type: input
    attributes:
      label: Version
      description: Please specify the exact Go module version you're reporting for.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: To reproduce
      description: A code snippet to reproduce the problem described above.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: |
        Links? References? Suggestions? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://go.dev/conduct)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
