name: Documentation
description: Suggest an idea or a patch for documentation
labels: ["📖 documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this form!
  - type: textarea
    attributes:
      label: What is missing or wrong? Please describe
      description: A clear and concise description of what the problem is, e.g. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Why do you think it is important?
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://golang.org/conduct)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
